### ISSUE TITLE
Handling self-referential objects

### ISSUE THREAD

**Issue by ZacSweers** [utwyko/KMinRandom#2]
Does KMinRandom handle self-referential objects?

```kotlin
data class SelfReferential(val ref: SelfReferential)
```

**Comment by ZacSweers** [comment]
Just to clarify - I know this isn't technically feasible. I'm wondering more about detecting them :)

**Comment by utwyko** [comment]
Currently not well, it'll result in a `StackOverflowError`. I'll make sure to detect it early and throw a proper exception in the next release.

Thanks for pointing this out!

**Comment by utwyko** [comment]
@ZacSweers I've created a PR (#3) that should address this. Could you have a look at the test (https://github.com/utwyko/KMinRandom/pull/3/files#diff-42b9660d6a792fb81d608e8ea974d1ff) and let me know if this behaviour matches your expectations?

**Comment by ZacSweers** [comment]
Hello I'm late! Yes that looks perfect, thank you.

(sorry I was on sabbatical at the time of your response and missed this entirely)
